<script>
import {
  fetchUsers,
  fetchTasksByUser,
  deleteTask,
  fetchTaskById,
} from "@/services/api";
import SimpleTable from "@/pages/GenerateTaskTable.vue";
import OrderedTable from "@/components/Tables/CreatedTaskTable.vue";
import TaskDetailModal from "@/components/Modals/TaskDetailModal.vue";
import FilePreviewModal from "@/components/Modals/FilePreviewModal.vue";

export default {
  name: "TaskDashboard",
  components: {
    SimpleTable,
    OrderedTable,
    TaskDetailModal,
    FilePreviewModal,
  },
  data() {
    return {
      users: [],
      taskTypes: ["Meeting", "Follow-up", "Personal", "Reminder"],
      tasks: [],
      currentUser: {},
      previewFile: null, // full file URL for preview
      previewType: null, // "image" | "pdf" | "doc" | "other"

      // 🔹 New for popup
      selectedTask: null,
      showTaskModal: false,
    };
  },
  async created() {
    const savedUser = localStorage.getItem("user");
    if (savedUser) this.currentUser = JSON.parse(savedUser);

    try {
      this.users = await fetchUsers();
      await this.loadTasks();
    } catch (err) {
      console.error("❌ Error fetching data:", err.message);
    }
  },
  methods: {
    async loadTasks() {
      if (!this.currentUser.userId) return;
      try {
        const tasks = await fetchTasksByUser(this.currentUser.userId);
        this.tasks = tasks;
      } catch (err) {
        console.error("❌ Error fetching tasks:", err.message);
      }
    },
    async handleTaskAdded() {
      await this.loadTasks();
    },
    async deleteTaskHandler(taskID) {
      try {
        await deleteTask(taskID);
        this.tasks = this.tasks.filter((t) => t.worktaskId !== taskID);
        alert("Task deleted successfully");
      } catch (err) {
        console.error("Failed to delete task:", err);
        alert("Failed to delete task");
      }
    },

    /** Updated viewTask to open modal instead of alert */
    async viewTask(task) {
      try {
        const latestTask = await fetchTaskById(task.worktaskId);
        if (!latestTask) {
          alert("Task not found or has been deleted.");
          return;
        }
        this.selectedTask = latestTask;
        this.showTaskModal = true;
      } catch (err) {
        console.error("Failed to fetch task:", err);
        alert("Failed to fetch task details.");
      }
    },

    /** Handle file preview from modal */
    handleViewFile() {
      if (!this.selectedTask) return;

      console.log(this.selectedTask);

      console.log("📂 Raw filePath from DB:", this.selectedTask.filePath);
      console.log("🌐 Constructed fileURL:", fileURL);

      let fileURL = this.selectedTask.filePath
        ? `http://localhost/backend-systemPHP/${this.selectedTask.filePath}`
        : this.selectedTask.link || null;

      if (!fileURL) {
        alert("No file uploaded for this task.");
        return;
      }

      const fileExtension = fileURL.split(".").pop().toLowerCase();
      const imageExtensions = ["jpg", "jpeg", "png", "gif", "bmp", "webp"];
      const officeExtensions = ["doc", "docx", "xls", "xlsx", "ppt", "pptx"];

      if (imageExtensions.includes(fileExtension)) {
        this.previewFile = encodeURI(fileURL);
        this.previewType = "image";
      } else if (fileExtension === "pdf" || fileExtension === "txt") {
        this.previewFile = encodeURI(fileURL);
        this.previewType = "pdf";
      } else if (officeExtensions.includes(fileExtension)) {
        this.previewFile = encodeURI(fileURL);
        this.previewType = "doc";
      } else {
        window.open(fileURL, "_blank");
      }
    },

    closeTaskModal() {
      this.showTaskModal = false;
      this.selectedTask = null;
    },

    closePreview() {
      this.previewFile = null;
      this.previewType = null;
    },
  },
};
</script>

<template>
  <div class="content">
    <div class="md-layout">
      <!-- Generate Task -->
      <div
        class="md-layout-item md-medium-size-100 md-xsmall-size-100 md-size-100"
      >
        <md-card>
          <md-card-header data-background-color="green">
            <h4 class="title">Generate Task</h4>
            <p class="category">Create a new task or alert</p>
          </md-card-header>
          <md-card-content>
            <simple-table
              :users="users"
              :task-types="taskTypes"
              :current-user="currentUser"
              @task-added="handleTaskAdded"
            />
          </md-card-content>
        </md-card>
      </div>

      <!-- Task History -->
      <div
        class="md-layout-item md-medium-size-100 md-xsmall-size-100 md-size-100"
      >
        <md-card class="md-card-plain">
          <md-card-header
            data-background-color="green"
            class="header-with-action"
          >
            <div>
              <h4 class="title">Created Tasks</h4>
              <p class="category">Tasks generated by you</p>
            </div>
          </md-card-header>
          <md-card-content>
            <ordered-table
              v-if="tasks.length > 0"
              :tasks="tasks"
              @delete-task="deleteTaskHandler"
              @view-task="viewTask"
            />
            <p v-else>No tasks available</p>
          </md-card-content>
        </md-card>
      </div>
    </div>

    <!-- Task Detail Modal -->
    <task-detail-modal
      :show="showTaskModal"
      :task="selectedTask"
      @close="closeTaskModal"
      @view-file="handleViewFile"
    />

    <!-- Preview Modal -->
    <file-preview-modal
      :show="!!previewFile"
      :type="previewType"
      :file-url="previewFile"
      @close="closePreview"
    />
  </div>
</template>

<style scoped>
.header-with-action {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
</style>
